package babycareai.backend.domain.diagnosis.enums;

import lombok.Getter;

@Getter
public enum Symptoms {

    ACHES_AND_PAINS("쑤시고 아픔"),
    ALLERGIC_REACTIONS("알레르기 반응"),
    ANNOYANCE("짜증"),
    BAD_BREATH("구취"),
    BLISTERS("물집"),
    BLOTCHY_RASH("얼룩덜룩한 발진"),
    BLEEDING("출혈"),
    BURROWS("굴 같은 자국"),
    COUGH("기침"),
    CRACKED_SKIN("갈라진 피부"),
    CRYING_DURING_NAPPY_CHANGES("기저귀 갈 때 울음"),
    CRUSTY_EYELASHES("딱딱한 속눈썹"),
    DISCHARGE_FROM_EYES("눈 분비물"),
    DIFFICULTY_HEARING("청각 곤란"),
    DIFFICULTY_SWALLOWING("삼킴 곤란"),
    DIARRHOEA("설사"),
    DIMPLE_IN_CENTER_OF_SPOTS("반점 중앙의 보조개"),
    DISCOMFORT("불쾌감"),
    DROOLING("침 흘림"),
    DRYNESS_EYES("눈 건조"),
    DRY_SKIN("건조한 피부"),
    EARACHE("귀앓이"),
    EYE_IRRITATION("눈 자극"),
    FEVER("열"),
    FLAKY_SKIN("껍질이 벗겨지는 피부"),
    FLARE_UPS_ECZEMA("악화 (습진)"),
    FLU_LIKE_SYMPTOMS("독감 유사 증상"),
    FLUID_FILLED_BLISTERS("수포"),
    GREASY_SCALES("기름진 비늘"),
    GRITTINESS_EYES("눈의 이물감"),
    GRIZZLY("칭얼거림"),
    HAIR_LOSS_SCALP("탈모 (두피)"),
    HEADACHE("두통"),
    IRRITABILITY("과민성"),
    IRRITATION("자극"),
    ITCHING("가려움증"),
    ITCHY_SKIN("가려운 피부"),
    ITCHY_EYES("가려운 눈"),
    ITCHY_RASH("가려운 발진"),
    ITCHY_BUMPS("가려운 덩어리"),
    JAUNDICE("황달"),
    LETHARGIC("무기력함"),
    LOSS_OF_APPETITE("식욕 부진"),
    MILD_DIARRHOEA("경미한 설사"),
    MUSCLE_ACHES("근육통"),
    NAUSEA("메스꺼움"),
    PAIN("통증"),
    PAINFUL_BLISTERS("통증성 물집"),
    PAINLESS_BUMP("통증 없는 혹"),
    PEELING_SKIN("피부 벗겨짐"),
    PINK_EYE("결막염"),
    PIMPLES("여드름"),
    PIMPLY_RASH("여드름성 발진"),
    PUFFY_EYES("부은 눈"),
    PUS_FILLED_SPOTS("고름 찬 반점"),
    RAISED_BUMPS("솟아오른 덩어리"),
    RAISED_PATCHES("솟아오른 반점"),
    RASH("발진"),
    RED_BUMPS("붉은 덩어리"),
    RED_RASH("붉은 발진"),
    RED_SPOTS("붉은 반점"),
    RED_SKIN("붉은 피부"),
    RED_EYES("붉은 눈"),
    REDNESS("붉어짐"),
    RELUCTANCE_TO_FEED("수유 거부"),
    RING_SHAPED_RASH("고리 모양 발진"),
    RUNNY_NOSE("콧물"),
    SCALY_PATCHES("비늘 모양 반점"),
    SCALY_SKIN("비늘 모양 피부"),
    SMALL_BLISTER_LIKE_SORES("작은 물집 같은 염증"),
    SMALL_YELLOW_WHITE_PUSTULES("작은 황백색 농포"),
    SNEEZING("재채기"),
    SORE_EYES("눈의 통증"),
    SORE_MOUTH("입의 통증"),
    SORE_THROAT("목의 통증"),
    SORENESS("쓰림"),
    SORES("염증"),
    SPREADING_RASH("번지는 발진"),
    STICKY_EYELIDS("끈적거리는 눈꺼풀"),
    SUDDEN_FEVER("갑작스러운 발열"),
    SWELLING("부기"),
    SWOLLEN_GUMS("부은 잇몸"),
    SWOLLEN_GLANDS("부은 샘"),
    SWOLLEN_LYMPH_GLANDS("부은 림프샘"),
    SWOLLEN_NECK_GLANDS("부은 목 샘"),
    TIREDNESS("피로"),
    TINY_RAISED_SPOTS("작은 솟아오른 반점"),
    TUGGING_AT_EAR("귀 잡아당김"),
    UNUSUAL_TIREDNESS("평소와 다른 피로"),
    WARM_TO_TOUCH("만졌을 때 따뜻함"),
    WATERY_EYES("눈물"),
    WHITE_COATING_ON_TONGUE("혀의 백태"),
    WHITE_PATCHES("하얀 반점"),
    WHITEHEADS("좁쌀 여드름");

    private final String koreanName;

    Symptoms(String koreanName) {
        this.koreanName = koreanName;
    }

}